@startuml
'style
title ltpa login authentication sequence
hide footbox

'participant
actor User
participant Request
participant LtpaAuthenticator
participant Authenticator
participant TokenService
participant TokenFactory
database LDAP
participant Response

User -> Request : logout(user,passwd);
Request -> LtpaAuthenticator : logout();
LtpaAuthenticator -> LtpaAuthenticator : register(null);
LtpaAuthenticator -> TokenService : cleanLtpaToken();
TokenService -> Request : getResponse();
Request --> TokenService : response
TokenService -> Response : addCookie(LtpaToken,maxAge=0);
Response --> TokenService
TokenService --> LtpaAuthenticator
LtpaAuthenticator -> Authenticator : logout();
Authenticator --> LtpaAuthenticator
LtpaAuthenticator --> Request : logout success
Request --> User : logout page

@enduml